language: python
install: 
- lscpu
- pip install -e .
script: py.test

python:
    - "pypy"
    - "pypy3"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6" 

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "3.8-dev"
      dist: xenial
      sudo: true
    - arch: arm64  
      python: "2.7"
    - arch: arm64
      python: "3.3"
    - arch: arm64
      python: "3.4"
    - arch: arm64
      python: "3.5"
    - arch: arm64
      python: "3.6" 
    - arch: arm64
      python: "3.7"
      dist: xenial
      sudo: true
    - arch: arm64
      python: "3.8-dev"
      dist: xenial
      sudo: true
